#!/usr/bin/python3
import base64
import sys
from Crypto.Cipher import AES


def throw(msg, name=sys.argv[0]):
    print('%s:' % name, msg, file=sys.stderr)
    sys.exit(84)


def main(args):
    if len(args) != 2:
        throw('Invalid arguments')
    try:
        with open(args[1], 'r') as f:
            data = [base64.b64decode(line) for line in f]
            if len(data) == 0:
                raise ValueError()
            if any(len(d) % 16 != 0 for d in data):
                raise ValueError()
    except IOError as e:
        throw('Cannot read file: %s' % e.strerror, name=args[1])
    except ValueError:
        throw('Invalid file context', name=args[1])

    data = [[d[i:i+16] for i in range(0, len(data))] for d in data]
    line = max(enumerate(data), key=lambda x: sum(
        x[1].count(b) for b in x[1]))[0]
    print(line + 1)


if __name__ == '__main__':
    main(sys.argv)
