#!/usr/bin/python3
import base64
import re
import sys


def throw(msg, name=sys.argv[0]):
    print('%s:' % name, msg, file=sys.stderr)
    sys.exit(84)


def main(args):
    if len(args) != 2:
        throw('Invalid arguments')
    try:
        with open(args[1], 'r') as f:
            x = bytes.fromhex(re.sub(r'\s', '', f.read()))
            if len(x) == 0:
                raise ValueError()
    except IOError as e:
        throw('Cannot read file: %s' % e.strerror, name=args[1])
    except ValueError:
        throw('Invalid file context', name=args[1])

    print(base64.b64encode(x).decode())


if __name__ == '__main__':
    main(sys.argv)
