#!/usr/bin/python3
import re
import sys


def throw(msg, name=sys.argv[0]):
    print('%s:' % name, msg, file=sys.stderr)
    sys.exit(84)


def main(args):
    if len(args) != 2:
        throw('invalid arguments')
    try:
        with open(args[1], 'r') as f:
            key = bytes.fromhex(re.sub(r'\s', '', f.readline()))
            data = bytes.fromhex(re.sub(r'\s', '', f.read()))
            if len(key) == 0 or len(data) == 0:
                raise ValueError()
    except IOError as e:
        throw('Cannot read file: %s' % e.strerror, name=args[1])
    except ValueError:
        throw('Invalid file context', name=args[1])

    print(bytes(data[i] ^ key[i % len(key)]
                for i in range(len(data))).hex().upper())


if __name__ == '__main__':
    main(sys.argv)
