#!/usr/bin/python3
import re
import sys


def throw(msg, name=sys.argv[0]):
    print('%s:' % name, msg, file=sys.stderr)
    sys.exit(84)


def main(args):
    if len(args) != 2:
        throw('Invalid arguments')
    try:
        with open(args[1], 'r') as f:
            x = bytes.fromhex(re.sub(r'\s', '', f.readline()))
            y = bytes.fromhex(re.sub(r'\s', '', f.readline()))
            if len(x) == 0 or len(x) != len(y):
                raise ValueError()
    except IOError as e:
        throw('Cannot read file: %s' % e.strerror, name=args[1])
    except ValueError:
        throw('Invalid file context', name=args[1])

    print(bytes(x ^ y for x, y in zip(x, y)).hex().upper())


if __name__ == '__main__':
    main(sys.argv)
